AllCops:
  Exclude:
    - '.bundle/**/*'
    - 'vendor/**/*'
    # We shouldn't need the above but for now there's a bug in rubocop

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

Encoding:
  Enabled: false

HashSyntax:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

ParameterLists:
  Enabled: false
