require:
- rubocop-performance
- rubocop-rails

AllCops:
  Exclude:
    - '.bundle/**/*'
    - 'vendor/**/*'
    # We shouldn't need the above but for now there's a bug in rubocop
    - 'lib/admin/dropsonde_protocol/*'
    - 'spec/support/ccdb/*'
    - 'spec/support/uaadb/*'

AbcSize:
  Enabled: false

AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

BlockLength:
  Enabled: false

BlockNesting:
  Enabled: false

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

ParameterLists:
  Enabled: false

PerceivedComplexity:
  Enabled: false

Rails/Exit:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RescuedExceptionsVariableName:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

UncommunicativeMethodParamName:
  Enabled: false

UriEscapeUnescape:
  Enabled: false
