inherit_from:
  - ../.rubocop.yml

Layout/IndentFirstArrayElement:
  EnforcedStyle: align_brackets

Layout/IndentFirstHashElement:
  EnforcedStyle: align_braces

Lint/HandleExceptions:
  Enabled: false

Style/Lambda:
  Enabled: false