inherit_from:
  - ../.rubocop.yml

HandleExceptions:
  Enabled: false

IndentFirstArrayElement:
  EnforcedStyle: align_brackets

IndentFirstHashElement:
  EnforcedStyle: align_braces

Style/Lambda:
  Enabled: false