### Generated by rprotoc. DO NOT EDIT!
### <proto file: /home/user/workspace/dropsonde-protocol/events/envelope.proto>
# package events;
# option java_package = "org.cloudfoundry.dropsonde.events";
# option java_outer_classname = "EventFactory";
# 
# import "http.proto";
# import "log.proto";
# import "metric.proto";
# import "error.proto";
# 
# /// Envelope wraps an Event and adds metadata.
# message Envelope {
#     /// Type of the wrapped event.
#     enum EventType {
#         // Removed Heartbeat at position 1
#         HttpStart = 2;
#         HttpStop = 3;
#         HttpStartStop = 4;
#         LogMessage = 5;
#         ValueMetric = 6;
#         CounterEvent = 7;
#         Error = 8;
#         ContainerMetric = 9;
#     }
# 
#     required string origin = 1;               /// Unique description of the origin of this event.
#     required EventType eventType = 2;         /// Type of wrapped event. Only the optional field corresponding to the value of eventType should be set.
# 
#     optional int64 timestamp = 6;             /// UNIX timestamp (in nanoseconds) event was wrapped in this Envelope.
# 
#     optional string deployment = 13;          /// Deployment name (used to uniquely identify source).
#     optional string job = 14;                 /// Job name (used to uniquely identify source).
#     optional string index = 15;               /// Index of job (used to uniquely identify source).
#     optional string ip = 16;                  /// IP address (used to uniquely identify source).
# 
#     // Removed Heartbeat at position 3
#     optional HttpStart httpStart = 4;
#     optional HttpStop httpStop = 5;
#     optional HttpStartStop httpStartStop = 7;
#     optional LogMessage logMessage = 8;
#     optional ValueMetric valueMetric = 9;
#     optional CounterEvent counterEvent = 10;
#     optional Error error = 11;
#     optional ContainerMetric containerMetric = 12;
# }
# 

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Events
  ::Protobuf::OPTIONS[:"java_package"] = "org.cloudfoundry.dropsonde.events"
  ::Protobuf::OPTIONS[:"java_outer_classname"] = "EventFactory"
  require 'http.pb'
  require 'log.pb'
  require 'metric.pb'
  require 'error.pb'
  class Envelope < ::Protobuf::Message
    defined_in __FILE__
    class EventType < ::Protobuf::Enum
      defined_in __FILE__
      HttpStart = value(:HttpStart, 2)
      HttpStop = value(:HttpStop, 3)
      HttpStartStop = value(:HttpStartStop, 4)
      LogMessage = value(:LogMessage, 5)
      ValueMetric = value(:ValueMetric, 6)
      CounterEvent = value(:CounterEvent, 7)
      Error = value(:Error, 8)
      ContainerMetric = value(:ContainerMetric, 9)
    end
    required :string, :origin, 1
    required :EventType, :eventType, 2
    optional :int64, :timestamp, 6
    optional :string, :deployment, 13
    optional :string, :job, 14
    optional :string, :index, 15
    optional :string, :ip, 16
    optional :HttpStart, :httpStart, 4
    optional :HttpStop, :httpStop, 5
    optional :HttpStartStop, :httpStartStop, 7
    optional :LogMessage, :logMessage, 8
    optional :ValueMetric, :valueMetric, 9
    optional :CounterEvent, :counterEvent, 10
    optional :Error, :error, 11
    optional :ContainerMetric, :containerMetric, 12
  end
end